### ISSUE TITLE
Add support for exported symbols without names

### ISSUE THREAD

**Issue by gtker** [N0fix/rpecli#1]
Functions can be exported with ordinals only. This is supported by the official `dumpbin` util, but `rpecli` just reports `0 exported function(s)`.

I can provide an example file if necessary.

**Comment by N0fix** [comment]
Hello,

Please provide your target executable so I can reproduce the behavior.

**Comment by gtker** [comment]
This file reports no exports with `rpeclit`, but >200 with `dumpbin`.

[Storm.zip](https://github.com/N0fix/rpecli/files/13753902/Storm.zip)

**Comment by N0fix** [comment]
Thanks, this should be fixed by next week

**Comment by N0fix** [comment]
This is fixed in master. I am waiting for authenticode crate to publish an update to creates.io so that I can publish mine.

**Comment by N0fix** [comment]
This should be fixed with [fbdf577](https://github.com/N0fix/rpecli/commit/fbdf577151480940b656ad77765cb2fb615af0ce)
