### ISSUE TITLE
Add easy to use interface for iterating through exports

### ISSUE THREAD

**Issue by gtker** [N0fix/rpecli#3]
This probably ties in with #1 and #2.

None of the current libraries seem to make this easy to do. I noticed [this function in the library](https://github.com/N0fix/rpecli/blob/0fbf6241c9bbdaecf5628889d720524a1b51bf78/src/import_export.rs#L65), but it doesn't work for exports without a name.

I basically just need what `dumpbin` does, which just a `Vec` of either a struct or tuple of with the ordinal number, name, and RVA.

**Comment by N0fix** [comment]
See #1 and #2
